# .github/workflows/firebase-distribution.yml
name: Archive Build Artifacts

on:
  workflow_call:
    inputs:
      artifact-path:
        required: true
        type: string
    secrets:
      EXPO_TOKEN:
        required: true

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Download APK from EAS
        run: |
          mkdir -p "${{ inputs.artifact-path }}"
          FILE_PATH="${{ inputs.artifact-path }}/app-release.apk"

          eas build:list --limit 1 --status=finished --platform android --json > builds.json
          URL=$(jq -r '.[0].artifacts.buildUrl' < builds.json)
          
          # Save file to folder
          curl -L -o "$FILE_PATH" "$URL"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: "${{ inputs.artifact-path }}/app-release.apk"
