name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Run Expo bundle check
        run: npx expo export --platform android --dev --output-dir temp-build

      - name: Run Code Coverage Analysis
        run: npm run coverage

      - name: Run Unit Tests
        run: npm test

      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"✅ Build succeeded on *${{ github.ref_name }}* by *${{ github.actor }}*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View build run>\"
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"❌ Build failed on *${{ github.ref_name }}* by *${{ github.actor }}*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View build run>\"
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
